### ISSUE TITLE
Replacing email addresses as mailto links in README

### ISSUE THREAD

**Issue by ItsPugle** [gatsbyjs/store.gatsbyjs.org#164]
Hey,

I know this is a really basic thing, but does anyone have any reason why they wouldn't be okay with this? Having the email address as is is a bit disruptive to what could be a perfect tone of voice example, but having it hyperlinked would be better. 

For example, instead of `Send us an email to team@gatsbyjs.org and we'll see what we can do` which is a bit odd/unusual, we could have `Just [send us an email](mailto:team@gatsbyjs.org), and we'll see what we can do`.

If no one have any objections, I'll get cracking on a PR straight away 🙂

**Comment by DSchau** [comment]
Doesn't it already work this way?

![screen shot 2018-11-02 at 9 56 09 am](https://user-images.githubusercontent.com/3924690/47922643-89e06000-de85-11e8-9f7d-ecc8694bc3e7.png)

**Comment by ItsPugle** [comment]
Hey @DSchau,

Sorry, I think I might have explained this wrong! What I'm thinking is that instead of having the email written inline, the text "send us an email" etc would by hyperlinked:
![2018-11-03 at 11 26 am](https://user-images.githubusercontent.com/22669894/47946839-0abe5b00-df5d-11e8-954f-3cbe3eba2650.png)

Most companies that I've looked at prefer to hyperlink text with related articles or actions (i.e. contact forms) than providing the URL as a separate chunk of text 🙂

**Comment by jlengstorf** [comment]
@ItsPugle I've found that `mailto` links are sometimes weird. For example, I hate it when I click on one and the "Mail" app opens when what I actually wanted was to send through my browser. Being able to read the email as text helps people like me who might be transcribing it from the screen to my phone, etc.

Same with the Twitter handle: I like to see what the account is.

That being said, I don't have strong opinions about this, and I'm open to being convinced otherwise.
