### ISSUE TITLE
Look into smaller images from the Shopify API for cart preview

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#18]
The cart preview image takes a while to load, for the dark deploy shirt it's a 3000px square image that gets displayed at 35px square

https://user-images.githubusercontent.com/381801/41650716-a4ce1eda-7476-11e8-9972-996d36413a18.png

**Comment by jlengstorf** [comment]
This isn't _entirely_ fixed, but I shrunk down all the images to be 1024x1024. We're still going to see more image transfer than necessary, but it should be much less ridiculous now. We should still look into a better solution for this, but I don't want to make this a blocker.

Rather than closing this, I'm going to move it to Phase 2.

**Comment by coreyward** [comment]
@jlengstorf Is there not a transformer to fetch a remote image (i.e., in GraphQL, something that allows using `gatsby-transformer-sharp` on a local image that was fetched from a remote URL specified in a node)?

**Comment by jlengstorf** [comment]
@coreyward There is! We're using that for the shop images.

This issue is tracking the dynamic part of the store, which is adding items to the cart. That's done by calling the Shopify API, which returns data about the cart items, including its URL.

What we need to do is figure out how to map the URL returned by Shopify to the images generated by Gatsby.

My current assumption is that it'll work something like this:

- As we build the shop, we grab an ID for each product and create a hash table for the generated images, like so:
	
	```js
    const images = [
      [PRODUCT_ID]: {
        "size1": "path/to/image.jpg",
        // ... all sizes here ...
      },
      // ... the rest of the products ...
    ];
    ```
- Put that somewhere we can look it up, e.g. in a script tag appended to the body (haven't thought hard about this; there's probably a better way)
- When cart items are added, look up the appropriate images by product ID and use that instead of the Shopify image URL

I haven't really dug into it yet, but this is my current assumption.

If anyone wants to take a shot at this, I'm happy to run support/code review!

**Comment by coreyward** [comment]
What about a `ProductImage` component that uses StaticQuery to assemble/maintain the map between product IDs and photos that adds a `src` prop to the child(ren)? Or it can accept a function as children or a render prop if preferred.

Example usage:

```jsx
<ProductImage id={productId} fallback={giantImageSrc}>
  <Image alt={productName} />
</ProductImage>
```

Where ProductImage is doing something like…

```js
const mapped_product_image = this.products[this.props.id] || this.props.fallback
return React.cloneElement(children, { src: mapped_product_image })
```

If that looks good I can take a stab at it.

**Comment by jlengstorf** [comment]
Oh, nice. So you're thinking the `StaticQuery` would put together the list of all available products/images and `ProductImage` would run a `find` (or whatever) to pull out the Gatsby image?

Yeah, I think that would work way better than what I said. 😅 

Thanks for jumping in! Let me know if I can help.
