### ISSUE TITLE
[redesign] Finish/fix community captions

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#205]
Because of https://github.com/gatsbyjs/store.gatsbyjs.org/pull/201#discussion_r244872315 I'm not really sure about the current status of the functionality. 

The caption field on Shopify would be the best solution. But if not we can still use `altText` with some hack. 

If the value of `altText` would have a structure like below: 

```
altText: "This is real altText [And this is a community capiton] 
```
so if we find the `[......]` pattern inside `altText` we show the caption if not we do not. 

BTW. the `alt` props of images are empty for now, I forgot about them.

There is also an issue with the current code of the caption on iOS, I did not make it today.

Toggling the widget breaks it. 

![screenshot from 2019-01-03 17-40-31](https://user-images.githubusercontent.com/32480082/50649650-c2341580-0f7e-11e9-8e07-981d5ea10af3.png)
 
On android it works fine, but not on iOS. I had no chance to figure out what's the problem.

**Comment by jlengstorf** [comment]
For now, I think we should leave captions off — it's not urgent, and I'm worried about creating our own programming language with patterns, etc. The likelihood of accidentally breaking things is too high, especially as we scale.

I looked for Shopify plugins, and as far as I can tell there's nothing that adds extra fields — it was either really heavy image carousel stuff or "add more options", which we could maybe hack, but seems like it could also be harder to manage than we want it to be.

Currently I think extending the GraphQL API to have a `setCaption(image_id: ID!): Caption!` and `getCaption(image_id: ID!): Caption!` would be the simplest path forward since we've already got all of the foundations in place. This also makes it easier (in the future) to accept incoming image submissions, etc. since custom image data will be centralized.
