### ISSUE TITLE
Make it clear that logging in is only possible with a GitHub account

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#22]
It should be more obvious that the only way to log in is with your GitHub account.

**Comment by jlengstorf** [comment]
Adding the text is probably good for now. I don't think we should commit to working on a non-GitHub version until we've verified that we're able to support that.

**Comment by marisamorby** [comment]
@fk  @jlengstorf 

Just a note here, I added a blocker to this task. We'll want the lo-fi prototype to be done and agreed on before we start thinking about this interaction.

**Comment by fk** [comment]
Hey y'all! Let's start this off with Flo (shamefully) ignoring the blocking issue (#43). 🎉 🙄 🙏 

I did so because I had everything in place for this particular thing and felt like it would be good to familiarize myself with Figma and its prototyping tools before starting with #43. Poor excuse, I know… FWIW I don't think #43 and this should affect each other much? Will stick to the script from now on!

---

So here's a "screen size lowest common denominator" clickable Figma prototype showing

* the log in button with GitHub logo and "Log in with GitHub" text and
* the callout from https://github.com/gatsbyjs/store.gatsbyjs.org/issues/15#issuecomment-401044859 to inform users/contributors about "free swag" and "log in with your Github account":

https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=1%3A2&scaling=min-zoom lets you log in and open the dropdown menu for the logged in user.

The current design also shows a possible option to make the header with navigation, shopping cart and login button/user profile fit on a 320px-wide screen by dropping the links to "Swag Store" and "Dashboard", and by omitting the "Gatsby" wordmark. If we want to keep these around for small devices, I don't see a much better solution than adding a hamburger button to the header (although we could try to overflow-scroll the navigation items a la reactjs.org—we'd have to drop the "Store" and username at least on the very small screens though).

On larger screens we can show the "Gatsby" wordmark and increase font sizes for the button and username: https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=28%3A1&scaling=min-zoom

**Comment by jlengstorf** [comment]
This looks great, @fk! I think we can establish the user areas as part of
the profile drop-down, and make that part of the universal header UI
pattern.

This is truly excellent work. Thanks!
-- 

*Jason Lengstorf*
Find me online: *Twitter <https://twitter.com/jlengstorf>* · GitHub
<https://github.com/jlengstorf> · *LinkedIn
<https://linkedin.com/in/jlengstorf/>*
Oversharing at *lengstorf.com <https://lengstorf.com/>*

**Comment by marisamorby** [comment]
Closing this out!
