### ISSUE TITLE
Couldn't start the project

### ISSUE THREAD

**Issue by hillarysousa** [gatsbyjs/store.gatsbyjs.org#292]
I've forked and cloned the project, but when I try to build it or even start it, it gives me an error. 

Apparently, there is something wrong with the Shopify integration, but I couldn't figure out what is happening.

![image](https://user-images.githubusercontent.com/10313411/66182650-55a09100-e64c-11e9-80d0-b5f297949a2a.png)

**Comment by amolmt** [comment]
I'm facing the same issue!

**Comment by amolmt** [comment]
I tried but couldn't fix it. I think this issue is related to Shopify client ID which is in .env.dev 
GraphQL is not being able to query allShopifyProducts so the issue has to be in .env or Auth0

**Comment by imagentleman** [comment]
@hillarysousa @amolmt Did you by any chance use npm instead of yarn? This also happened to me, but i noticed that the project doesn't have a package-lock.json but a yarn.lock, so tested with yarn and the project ran successfully. 

My guess is that with npm since there isn't a lock file with the right versions of the dependencies, when you run npm install a dependency with a wrong version (an updated one with breaking changes) ruins the build.

**Comment by hillarysousa** [comment]
Hmmm yeah. I ran it with NPM. I'll test it with Yarn.

Em sáb, 5 de out de 2019 11:18, José Antonio Chio <notifications@github.com>
escreveu:

**Comment by mihaiserban** [comment]
indeed there's a yarn.lock file which locks the versions of the packages. You could as well lock the version in the package.json like so:

"gatsby-source-shopify": "2.0.30",
"shopify-buy": "2.2.4",

**Comment by marquez138** [comment]
Hi did this issue get solved? Im also having this error even after yarn install
