### ISSUE TITLE
Add a next step to the "order complete" screen

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#30]
Should this link back to the home page? Somewhere else? Maybe Twitter?

**Comment by fk** [comment]
Could be both. ;-)

I'd definitely do Twitter because that'd be the place where we would announce new stuff available in the store (or restock), right? "Follow on Twitter to know when we add new stuff to the store".

Also thought about s/th along the way of "Thank you for contributing to Gatsby. We hope you like your free swag! Even if we are not able to give out more free stuff, we'd love you to stick around contributing to Gatsby! ;-)" for orders with a coupon code.

For purchases without a coupon code, we should IMO thank people for their support and clearly state what will happen with the money that we make—if we actually are. ;-)

**Comment by jlengstorf** [comment]
I can't find anywhere to edit the order confirmation screen in Shopify. Unless someone wants to take this on, I'm going to close it.
