### ISSUE TITLE
There is no longer account.js

### ISSUE THREAD

**Issue by ThewBear** [gatsbyjs/store.gatsbyjs.org#318]
The Gatsby store `account.js` is mentioned everywhere in the Docs for client-only route. Since 7cd87cb, it has been removed. Those docs need some updates.

There are also some codes in this repo which are no longer used such as
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/b2f186f50384f7466687f253cd2cb760e29ce783/gatsby-node.js#L61-L76

**Comment by Developerayo** [comment]
Hey, @ThewBear I left a comment on your opened issue on the gatsby repo, can you open a PR here to fix this here?

**Comment by jwu910** [comment]
Hi! :wave: , new to Gatsby, and just browsing to see if there were issues I could use to get familiar with the code base. This issue was one of the first that looked straight forward.

Looks like I might need updated shopify keys to get this set up locally,  based off the last changes, it looks like you got rid of the account/* routes and opted for the ProductListings as the home page.

If that's correct, could we just delete these comments? Since user account pages wouldn't be generated until after the user logs in?

**Comment by PruthviOpensource** [comment]
Hi! 👋 , new to Gatsby, and just browsing to see if there were issues I could use to get familiar with the code base. This issue was one of the first that looked straight forward.

Looks like I might need updated shopify keys to get this set up locally, based off the last changes, it looks like you got rid of the account/* routes and opted for the ProductListings as the home page.

If that's correct, could we just delete these comments? Since user account pages wouldn't be generated until after the user logs in?

**Comment by LekoArts** [comment]
This has been since fixed.
