### ISSUE TITLE
BUILDWITHGATSBY discount code isn’t available to you right now

### ISSUE THREAD

**Issue by Usamaliaquat123** [gatsbyjs/store.gatsbyjs.org#324]
I'm trying to add my swag code on https://store.gatsbyjs.org/  but it show's like this "BUILDWITHGATSBY discount code isn’t available to you right now". Ii found some solution on github i try but looks like it doesn't work...
![download](https://user-images.githubusercontent.com/33973828/75512238-97d4c100-59a5-11ea-9687-fb28161159b0.png)

**Comment by Usamaliaquat123** [comment]
PS : I use the same email use in **Github**

**Comment by xaviemirmon** [comment]
Hi, @Usamaliaquat123 

I don't have any affiliation with the GatsbyJS Store (so removing myself as an assignee) just added a couple of PRs to this repo. 

That said, I have run into this issue myself, and the problem was needing to use the same e-mail that I log in to Github with and not the one listed on my profile.   If that doesn't fix it, team@gatsbyjs.com were really helpful in getting to the bottom of my issue. 😄 

Hope that helps!
