### ISSUE TITLE
Lo-fi prototype testing for cart and layout updates of swag store

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#43]
@jlengstorf @fk

## Goal
* Understand what cart interaction and sizing chart interaction is the lowest effort and works best for people

## Problem
* We don't want to spend time creating a cart and sizing chart interaction that ultimately needs to be reworked due to complexity, design system issues, etc.

## Solution & Next Steps
* Create lo-fi prototypes of 3 different cart and sizing chart interactions that will work on both desktop and mobile.
* Prototypes will be tested by the team and a consensus reached as to which one best fits in to future design system and is easy to use
* Need to find a date that works for this meeting

## Prototype Testing Steps
1. Once prototype is set up, share it out to participants via an issue with a link
2.  Set a date for everyone to meet and go through a shared review
3. Facilitator will set up questions and guide meeting
    * review lasts one hour
    * 3 - 5 people can go through tasks and answer questions
    * additional participants observe and chime in with questions
    * questions to ask:
        * Show me how you would add an item to your cart
        * Show me how you would check to see if a small shirt would fit you
        * Show me how you would check out 
        * For any functionality that is not live or we don't want to actively test, as the person to "Tell me what you think would happen if [you made this action]"
4. Facilitator takes notes on patterns, what works, and what doesn't work
5. Agree on what changes should be made and complete updates

**Comment by fk** [comment]
Here's a first look at a clickable prototype (not Lo-Fi because I had all the design items ready ;-)): https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=69%3A16&scaling=min-zoom

It currently allows to

* open the cart with no products added
* close cart
* open the (empty) "Sizing Chart & Care Instructions" modal
* add the "Purple Logo Tee", size "LG—Unisex", to the cart
* proceed to checkout or close the cart, either via the its close button or the "Continue Shopping" link
* add "Dark Deploy Tee", size "LG—Unisex" to cart
* proceed to checkout or close the cart, either via the its close button or the "Continue Shopping" link

The ability to add a second item to the cart is to show off how an alternating "Successfully added item to cart" message would look like (as discussed in https://github.com/gatsbyjs/store.gatsbyjs.org/issues/46#issuecomment-401064190).
Please note that the UI shown after the "add 'Dark Deploy Tee', size 'LG—Unisex' to cart" action does only make sense if the "Purple Logo Tee" shirt has been added before.
I can fix that, but not sure if it's worth the effort of adding more to this:

![image.png](https://images.zenhubusercontent.com/5acf46f34b5806bc2bceca1c/1a3a23d8-9669-4e01-9ca8-015286a0f890)

**Comment by fk** [comment]
I just added another clickable prototype: https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=121%3A491&scaling=scale-down

This one does not open the cart when a product is added, but instead shows a "bottom sheet"-like info-panel. I'm not super happy with the design of either of the two "info-panel" variants, but they're good enough to convey the basic idea. 

This prototype also shows an alternative to the "cart dropdown" used in the first prototype—it shows the cart in a "side drawer" instead. I must have had native apps (where this is a perfectly fine pattern IMO) in the back of my head when doing that as just yesterday when working on #41 I was made painfully aware of the limitations of "modal"-like UI components on mobile browsers again. So…just ignore that part I guess. ;-)

PS: When opening up Figma today, I was welcomed with all product images showing the purple shirt (instead of socks and "Dark Deploy"); also I had to relink a couple of things because something went wrong on that end, too. :-(

**Comment by fk** [comment]
For those who are following along but don't want to click through, here's a couple of screenshots:

![image](https://user-images.githubusercontent.com/21834/42379468-0878735c-812b-11e8-8180-df951bd29c99.png)


![image](https://user-images.githubusercontent.com/21834/42379442-f632ff00-812a-11e8-8f65-b997f3793b35.png)

Alternative "Bottom sheet"-like info-panel shown when a product is added to the cart:

![image](https://user-images.githubusercontent.com/21834/42379494-18f68e30-812b-11e8-937c-ff369ba9babe.png)

![image](https://user-images.githubusercontent.com/21834/42379508-21942fac-812b-11e8-97f5-122973546f3f.png)

**Comment by fk** [comment]
@marisamorby Can be closed?

**Comment by marisamorby** [comment]
Yes, we can close this!

**Comment by fk** [comment]
🎉 😉
