### ISSUE TITLE
GraphQL error

### ISSUE THREAD

**Issue by varunzxzx** [gatsbyjs/store.gatsbyjs.org#48]
I am getting the following error when running `develop` or `build`:
```
error GraphQL Error Unknown field `allShopifyProduct` on type `RootQueryType`
file: /src/components/Store/ProductListings.js
```

**Comment by jlengstorf** [comment]
@varunzxzx I think this is due to the fact that we're using a local copy of the Shopify plugin right now (I need to open a PR against the other plugin).

Run this and I _think_ it'll start working for you:

```sh
cd plugins/gatsby-source-shopify-storefront/
yarn
yarn build
cd ../..
yarn develop
```

I'm about 99% sure that'll fix the problem, so I'm going to close this. If it doesn't work, please open a new issue and we'll go from there.

Thanks!
