### ISSUE TITLE
Revenue information on Gatsby store product page

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#63]
@fk @jlengstorf 

From our meeting this morning Flo mentioned that it may be a good idea to include a blurb on the store that any revenue we get from the swag store is going to be put back in the open source community.

My suggested wording is here:

> We're happy to have you here at Gatsby, and thanks so much for helping us out. Any money made from your purchase at our swag store goes right back in to the open source community to help with Gatsby events and workshops.

**Comment by jlengstorf** [comment]
We should probably be more clear than that. What I think is actually going to be true is that Gatsby Inc will take losses on swag due to covering international shipping fees. We're rounding prices to make the discount codes less complicated, so anything over the cost of production will help us cover a small portion of shipping costs.

Since we won't make any money, it feels misleading to say we'd put money from this into the open source community. We _are_, but we're doing that by paying for printing and shipping the swag; there's no revenue to reinvest, though; swag for Gatsby is less of a revenue-generation effort than a kinda-sorta marketing cost.

So maybe it could say:

> The money we charge for swag helps to cover production and shipping costs. In the unlikely event that Gatsby swag ends up turning a profit, we'll reinvest that money into the open source community.

**Comment by fk** [comment]
Here's a first attempt at a "info" section in the footer with Jason's suggested copy, plus…some stuff ;-) around:

![desktop hd](https://user-images.githubusercontent.com/21834/42382519-d68acae8-8134-11e8-8ef7-ee04fb883608.png)

**Comment by marisamorby** [comment]
Love the "About the Gatsby Store" section. I don't think we should mention that Gatsby is taking a loss on this since we're not sure that it's true, and also I don't think that as a business we want to discuss losses with the public. I'll let @jlengstorf make final approval on that though.
