### ISSUE TITLE
Review source code for dashboard and store and list open questions

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#68]
@fk 

On the call today you mentioned that you want to take a look at the way @jlengstorf implemented the design system and structure of the site.

Please list open questions in this PR and then you can decide if you want to have a meeting to discuss questions on Tuesday.

**Comment by fk** [comment]
I went through the source code and am happy to report no issues in terms of "where to change/add stuff".

I also started breaking down the design update/implementation adjustments into tasks and will add issues for that now. I think that this will serve us better than a "internal" meeting because it allows other people to chime in/be pinged and asked for feedback.

**Comment by jlengstorf** [comment]
This is great, @fk! Thanks!
