### ISSUE TITLE
Design system: Decide wether we want to use typography.js or not

### ISSUE THREAD

**Issue by fk** [gatsbyjs/store.gatsbyjs.org#69]
I'm unsure wether `rem`-based units for type serve us well in terms of "universal components"; I don't know if the latter is in scope of the design system we want to kick off here.

/cc @KyleAMathews @kkemple

**Comment by KyleAMathews** [comment]
Want to add tight integration between typography.js & styled-systems soon which will be nice as can use their `p` spacing thing. Though Typography.js already abstracts away from `rem` units with its `rhythm` unit.

**Comment by jlengstorf** [comment]
This seems like a broader question than the store. Maybe we can set up a meeting to discuss Gatsby's design system and figure out how we want to approach that? I know @kkemple has made some progress here — maybe we should consider putting it into its own repo or figuring out a "Gatsby public sites" monorepo pattern for the www/store/dashboards/design system/etc.?

Probably worth a dedicated discussion to make sure it scales as we build more and more sites in the Gatsby ecosystem.

**Comment by kkemple** [comment]
Yeah, this raises some interesting questions, good news for us is we don't really need mobile support (yet?...) and so using a web based measurement system is fine.

Does styled-system work with emotion as well as styled-components? Because if so it might not matter about web vs native for long because of this PR:

https://github.com/emotion-js/emotion/pull/759

**Comment by nitin42** [comment]
Yes, styled-system works with emotion!

According to their docs,

> Works with most css-in-js libraries, including styled-components, glamorous, emotion, fela, and cxs

**Comment by jlengstorf** [comment]
Closing this as stale.
