### ISSUE TITLE
Show alternating "Product added to cart" message

### ISSUE THREAD

**Issue by fk** [gatsbyjs/store.gatsbyjs.org#87]
After a product has been added to the cart, we currently open the cart to show its updated content(s).

In https://github.com/gatsbyjs/store.gatsbyjs.org/issues/46#issuecomment-401064190 (and following) we discussed showing an alternating "Added to cart" message:

* "Excellent Choice!"
* "That's going to look so good on you!"
* "We can't wait to see this on your Instagram."
* "Purple is your color."

https://www.figma.com/file/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=73%3A199 added a design for this message in the cart:

![image](https://user-images.githubusercontent.com/21834/42695646-5b2fa13e-86b6-11e8-9400-d087b9c0bb1b.png)

The design will be implemented in #86 by adding `src/components/cart/AddedToCart.js`.
This issue is tracking the implementation:

* show the message when adding a product to the cart
* after closing the cart and reopening the cart, the message shouldn't be displayed anymore
* when adding another product, a different message should show

**Comment by alex-saunders** [comment]
@jlengstorf Is this issue free to take & beginner-worthy?

**Comment by jlengstorf** [comment]
@alex-saunders It's free to take, yes! I _think_ it should be pretty beginner friendly as well.

This will have a few steps, so we could theoretically break it into pieces:

1. We need a component created and styled that looks the way @fk designed it in the screenshot above
2. We need a way to display that component _only_ when something has been added to the cart. This will be done by adding to the "add to cart" functionality.
3. We need a way to choose a message to show as each item is added. This could be done randomly or in sequence. My gut says random is probably plenty, since sequentially displaying them would require storing extra details in the state, which may be overkill for a just-for-fun feature.

Alex, if you want to take on one or more of these steps, we'd really appreciate it! Let me know if you have any questions, and if you need a code review please open a PR so we can take a look at the code.

Thanks!

**Comment by alex-saunders** [comment]
Hey @jlengstorf , thanks for the detailed reply!

I think this sounds like something I might be able to manage, would you be able to assign me to this issue and I'll have a crack at implementing it? I'll break the commits down into the steps you've outlined so that it's easier to review.

Cheers!

**Comment by jlengstorf** [comment]
@alex-saunders it looks like I can't assign it to you since you're not part of the GatsbyJS org (yet), so I'll leave it assigned to me, but we'll both know it's actually yours. 😄 

I've removed the help-seeking labels as well, so it's all yours!

**Comment by alex-saunders** [comment]
No problem @jlengstorf , I'll get cracking!

**Comment by alex-saunders** [comment]
hey @jlengstorf , just to keep you updated; I'm still working on this, I've just been super busy with work this past week!

**Comment by jlengstorf** [comment]
Sounds good. Thanks, @alex-saunders!

**Comment by jlengstorf** [comment]
With the new design, this isn’t really a thing anymore. It would be possible to add in fun messaging in the new design, but this particular approach doesn’t match the new design.

Closing, but happy to discuss alternatives if anyone is super excited about this.
